server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ # 集群名字
        namespace: 7dc209c9-a2a1-4831-ae7b-47e0d7661697
  application:
    name: orderservice
mybatis:
  type-aliases-package: com.zhuzi.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.zhuzi: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
