# 配置端口号，这里以10086为例
server:
  port: 10086

# 每个微服务都需要有名字，eureka也不例外，以后通过微服务的名字进行通信
spring:
  application:
    name: eureka-server

# 由于eureka服务器端也是一个微服务，所以也要配置注册地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
